PR for review
vmwhoami/weather_app pull request #1
Opened 2020-12-20 12:41 UTC by vmwhoami

The Weather App project comes at the end of the Asynchronous Javascript and APIs section of the Javascript course.
It tests the knowledge of the student about asynchronous communication with promises or async/await and when to use them.
Users can get weather information using API.

2020-12-20 13:35 UTC, bellom requested changes
## Hi @vmwhoami  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-12-20 13:35 UTC, bellom commented on src/scripts/async.js
> +    err.textContent = "Couldn't find your location";
Let's separate DOM related tasks from logic tasks.

You can create another method to handle DOM tasks.

![image](https://user-images.githubusercontent.com/31897434/73420341-70e18b80-4322-11ea-840a-fa14e04b592b.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/

2020-12-20 13:35 UTC, bellom commented on README.md
> +## Live Demo Website
Hey, Seems you forgot to add the live demo link.
Kindly add it 👍 .

2020-12-20 14:00 UTC, bellom requested changes
## Hi @vmwhoami  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-12-20 14:00 UTC, bellom commented on package.json
> +    "dotenv-webpack": "^6.0.0",
Inside this file.
we need to work on `script`
`npm start` seems not working.
Kindly double-check.

2020-12-20 14:00 UTC, bellom commented on src/scripts/queries.js
> +const weatherNow = (location) => `http://api.openweathermap.org/data/2.5/weather?q=${location}&APPID=${apikey}`;
Good job using `.env`
I think you don't need to use `.env`, this is just a weather app for you to display your knowledge on API calls.

2020-12-20 17:04 UTC, mosaaleb requested changes
#### Changes required

Well done @vmwhoami :clap:. You have handled all the requirements from the prevoius review. Yet there is a bug that prevents from showing the error message when the city is not found

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/error_handling_requirement.png)

- [ ] **[OPTIONAL]** it has a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API it has a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API 

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png)


Please handle this requirement and submit a new code review.

##### Muhammad Ebeid

2020-12-20 17:04 UTC, mosaaleb commented on src/scripts/async.js
> +    showError(error);
- [ ] This error message will never show up if the city is not found. The reason behind this is that the catch block will only catch errors due to a failure within fetch itself (network error, server not responding, ...). Any results come back from the server even if it fails to find a resource i.e 404 city not found won't be rejected. 
You can simulate a network error to check this in the dev console if you blocked the request domain:

![Screenshot from 2020-12-20 18-09-44](https://user-images.githubusercontent.com/4246637/102718045-b28a7480-42ee-11eb-8f9f-ed5eb2b2878d.png)

To get this issue solved we need to check if the `response` is `ok` and not 404.
My suggestion is to make this function just return data  wether the response succeeded or failed

```js
  try {
    const response = await fetch(url);

    if (!response.ok) {
      // rejected promise => catch block
      // you will still get json data from weather API even if the city is not found
      const dataError = await response.json();
      return Promise.reject(new Error(dataError.message));
    }

    // resolved promise => then block
    const data = await response.json();
    return data;

    // Can be moved to the function call in then block, check my next comment
    // populateDom(data);
    // const { lat } = data.coord;
    // const { lon } = data.coord;
    // await getPredictions(lat, lon, 'minutely,hourly');
  } catch (error) {
    // rejected promise => catch block
    return Promise.reject(new Error('network failure'));
  }
```

But you are free to handle this issue how you see fit.

2020-12-20 17:04 UTC, mosaaleb commented on src/scripts/events.js
> +      fetchData(searchloc);
- [ ] Then we can use `then` and `catch` blocks here to continue our data flow:

```js
fetchData(searchloc)
  .then((res) => {
    /* resolved promise */
    // handle successful response
    // populateData function
    // other logic
  })
  .catch((err) => {
    /* rejected promise */
    // showError(err)
  });
```

Resources : 
[fetch resolves even if 404?](https://stackoverflow.com/questions/39297345/fetch-resolves-even-if-404)
[Fetch Async Wait](https://dmitripavlutin.com/javascript-fetch-async-await/) 
[Promise reject vs throw](https://stackoverflow.com/questions/33445415/javascript-promises-reject-vs-throw)

2020-12-21 08:30 UTC, whiz25 approved these changes
## Approved :clap:
Nice work, @vmwhoami. You have made all the requested changes. Your app correctly displays and error when a city is not found. Well done.
You may merge this PR and continue to the next project. Good luck.


### Martin Afani

2020-12-21 12:53 UTC, merged